export type NeoItem = { id: number; text: string };
export const neoItems: NeoItem[] = [
  { id: 1, text: "No soy una persona que se preocupe mucho." },
  { id: 2, text: "La mayoría de la gente que conozco me cae muy simpática." },
  { id: 3, text: "Tengo una imaginación muy activa." },
  { id: 4, text: "Tiendo a ser cínico y escéptico respecto a las intenciones de los demás." },
  { id: 5, text: "Se me conoce por mi prudencia y sentido común." },
  { id: 6, text: "Con frecuencia me irrita la forma en que me trata la gente." },
  { id: 7, text: "Huyo de las multitudes." },
  { id: 8, text: "Los aspectos estéticos y artísticos no son muy importantes para él." },
  { id: 9, text: "No soy astuto ni disimulador." },
  { id: 10, text: "Prefiere dejar abiertas posibilidades más que planificarme todo de antemano." },
  { id: 11, text: "Rara vez me siento solo o triste." },
  { id: 12, text: "Soy dominante, enérgico y defiendo mis opiniones." },
  { id: 13, text: "Sin emociones fuertes la vida carecería de interés para mí." },
  { id: 14, text: "Algunas personas creen que soy egoísta y egocéntrico." },
  { id: 15, text: "Trato de realizar concienzudamente todas las cosas que se me encomiendan." },
  { id: 16, text: "Al tratar con los demás siempre temo hacer una patochada." },
  { id: 17, text: "Tanto en el trabajo como en la diversión tengo un estilo pausado." },
  { id: 18, text: "Tengo unas costumbres y opiniones bastante arraigadas." },
  { id: 19, text: "Preferiría cooperar con los demás a competir con ellos." },
  { id: 20, text: "No me enfado por nada, soy un poco pasota." },
  { id: 21, text: "Rara vez me excedo en algo." },
  { id: 22, text: "A menudo anhelo tener experiencias emocionantes." },
  { id: 23, text: "Con frecuencia disfruto jugando con teorías o ideas abstractas." },
  { id: 24, text: "No me importa hacer alarde de mis talentos y logros." },
  { id: 25, text: "Soy bastante bueno en organizarme para terminar las cosas a tiempo." },
  { id: 26, text: "Con frecuencia me siento indefenso y quiero que otro resuelva mis problemas." },
  { id: 27, text: "Literalmente, nunca he saltado de alegría." },
  { id: 28, text: "Considero que dejar que los jóvenes oigan a personas cuyas opiniones son polémicas sólo puede confundirles o equivocarles." },
  { id: 29, text: "Los líderes políticos deberían ser más conscientes del lado humano de sus programas." },
  { id: 30, text: "He hecho bastantes tonterías a lo largo de mi vida." },
  { id: 31, text: "Me asusto con facilidad." },
  { id: 32, text: "No me gusta mucho charlar con la gente." },
  { id: 33, text: "Intentó que todos mis pensamientos sean realistas y no dejar que vuele la imaginación." },
  { id: 34, text: "Creo que la mayoría de la gente tiene en general buena intención." },
  { id: 35, text: "No me tomo muy en serio mis deberes cívicos, como ir a votar." },
  { id: 36, text: "Soy una persona apacible." },
  { id: 37, text: "Me gusta tener mucha gente alrededor." },
  { id: 38, text: "A veces me quedo totalmente absorto en la música que escucho." },
  { id: 39, text: "Si es necesario, estoy dispuesto a manipular a la gente para conseguir lo que quiero." },
  { id: 40, text: "Tengo mis cosas bien cuidadas y limpias." },
  { id: 41, text: "A veces me parece que no valgo absolutamente nada." },
  { id: 42, text: "A veces no soy capaz de defender mis opiniones todo lo que debiera." },
  { id: 43, text: "Rara vez experimento emociones fuertes." },
  { id: 44, text: "Trato de ser cortés con todo el que conozco." },
  { id: 45, text: "A veces no soy tan formal y fiable como debiera." },
  { id: 46, text: "Rara vez me siento cohibido cuando estoy con gente." },
  { id: 47, text: "Cuando hago cosas, las hago con energía." },
  { id: 48, text: "Creo que es interesante aprender y desarrollar nuevas aficiones." },
  { id: 49, text: "Puedo ser sarcástico y mordaz si es necesario." },
  { id: 50, text: "Tengo unos objetivos claros y me esfuerzo por alcanzarlos de forma ordenada." },
  { id: 51, text: "Me cuesta resistirme a mis deseos." },
  { id: 52, text: "No me gustaría pasar las vacaciones en los centro de juego de Las Vegas." },
  { id: 53, text: "Encuentro aburridas las discusiones filosóficas." },
  { id: 54, text: "Prefiero no hablar de mis éxitos o de mi mismo." },
  { id: 55, text: "Pierdo mucho tiempo hasta que me pongo a trabajar." },
  { id: 56, text: "Creo que soy capaz de enfrentarme a la mayoría de mis problemas." },
  { id: 57, text: "A veces he experimentado una gran alegría o arrebato." },
  { id: 58, text: "Considero que las leyes y normas sociales deberían cambiar para reflejar las necesidades de un mundo cambiante." },
  { id: 59, text: "Soy duro y poco sentimental en mis actitudes." },
  { id: 60, text: "Pienso muy bien las cosas antes de tomar una decisión." },
  { id: 61, text: "Rara vez me siento con miedo o ansioso." },
  { id: 62, text: "Se me conoce como una persona cálida y cordial." },
  { id: 63, text: "Tengo mucha fantasía." },
  { id: 64, text: "Creo que la mayoría de la gente se aprovecharía de uno si se le dejara." },
  { id: 65, text: "Me mantengo informado y por lo general tomo decisiones inteligentes." },
  { id: 66, text: "Me consideran colérico y de genio vivo." },
  { id: 67, text: "En general prefiero hacer las cosas sólo." },
  { id: 68, text: "Me aburre el ballet clásico o danza moderna." },
  { id: 69, text: "Aunque quisiera, no podría engañar a nadie." },
  { id: 70, text: "No soy una persona muy metódica." },
  { id: 71, text: "Rara vez estoy triste o deprimido." },
  { id: 72, text: "A menudo he sido un líder en los grupos en que he estado." },
  { id: 73, text: "Cómo siento sobre las cosas es algo importante para mí." },
  { id: 74, text: "Algunas personas piensan de mí que soy frío y calculador." },
  { id: 75, text: "Pago mis deudas puntualmente y en su totalidad." },
  { id: 76, text: "En ocasiones he estado tan avergonzado que he querido esconderme." },
  { id: 77, text: "Probablemente mi trabajo sea lento pero constante." },
  { id: 78, text: "Cuando encuentro la manera de hacer algo, me aferro a ella." },
  { id: 79, text: "Me resulta difícil expresar rabia, aunque lleve razón." },
  { id: 80, text: "Cuando empiezo un programa para mejorar algo mío, lo habitual es que lo abandone a los pocos días." },
  { id: 81, text: "Me cuesta poco resistir a una tentación." },
  { id: 82, text: "A veces he hecho cosas por mera excitación, buscando emociones." },
  { id: 83, text: "Disfruto resolviendo problemas o rompecabezas." },
  { id: 84, text: "Soy mejor que la mayoría de la gente, y estoy seguro de ello." },
  { id: 85, text: "Soy una persona productiva, que siempre termina su trabajo." },
  { id: 86, text: "Cuando estoy bajo un fuerte estrés, a veces siento que me voy a desmoronar." },
  { id: 87, text: "No soy un alegre optimista." },
  { id: 88, text: "Considero que deberíamos contar con las autoridades religiosas para tomar decisiones sobre cuestiones morales." },
  { id: 89, text: "Hagamos lo que hagamos por los pobres y los ancianos, nunca será demasiado." },
  { id: 90, text: "En ocasiones primero actúo y luego pienso." },
  { id: 91, text: "A menudo me siento tenso e inquieto." },
  { id: 92, text: "Mucha gente cree que soy algo frío y distante." },
  { id: 93, text: "No me gusta perder el tiempo soñando despierto." },
  { id: 94, text: "Creo que la mayoría de la gente con la que trato es honrada y fidedigna." },
  { id: 95, text: "Muchas veces no preparo de antemano lo que tengo que hacer." },
  { id: 96, text: "No se me considera una persona quisquillosa o de mal genio." },
  { id: 97, text: "Si estoy solo mucho tiempo, siento mucha necesidad de la gente." },
  { id: 98, text: "Me despiertan la curiosidad las formas que encuentro en el arte y en la naturaleza." },
  { id: 99, text: "Ser absolutamente honrado no es bueno para los negocios." },
  { id: 100, text: "Me gusta tener cada cosa en su sitio, de forma que sepa exactamente dónde está." },
  { id: 101, text: "A veces he sentido una sensación profunda de culpa o pecado." },
  { id: 102, text: "En reuniones, por lo general prefiero que hablen otros." },
  { id: 103, text: "Rara vez pongo mucha atención en mis sentimientos del momento." },
  { id: 104, text: "Por lo general trato de pensar en los demás y ser considerado." },
  { id: 105, text: "A veces hago trampas cuando me entretengo con juegos solitarios." },
  { id: 106, text: "No me avergüenzo mucho si la gente se ríe de mí y me toma el pelo." },
  { id: 107, text: "A menudo siento como si estuviera explotando de energía." },
  { id: 108, text: "Con frecuencia pruebo comidas nuevas o de otros países." },
  { id: 109, text: "Si alguien no me cae simpático, se lo digo." },
  { id: 110, text: "Trabajo mucho para conseguir mis metas." },
  { id: 111, text: "Cuando como las comidas que más me gustan, tiendo a comer demasiado." },
  { id: 112, text: "Tiendo a evitar las películas demasiado violentas o terroríficas." },
  { id: 113, text: "A veces pierdo el interés cuando la gente habla de cuestiones muy abstractas y teóricas." },
  { id: 114, text: "Trato de ser humilde." },
  { id: 115, text: "Me cuesta forzarme a hacer lo que tengo que hacer." },
  { id: 116, text: "En situaciones de emergencia mantengo la cabeza fría." },
  { id: 117, text: "A veces reboso felicidad." },
  { id: 118, text: "En mi opinión, las distintas ideas sobre lo que está bien y lo que está mal que tienen otras sociedades pueden ser válidas para ellas." },
  { id: 119, text: "Los mendigos no me inspiran simpatía." },
  { id: 120, text: "Antes de emprender una acción, siempre considero sus consecuencias." },
  { id: 121, text: "Rara vez me inquieta el futuro." },
  { id: 122, text: "Disfruto mucho hablando con la gente." },
  { id: 123, text: "Me gusta concentrarme en un ensueño o fantasía y, dejándolo crecer y desarrollarse, explorar todas sus posibilidades." },
  { id: 124, text: "Cuando alguien es agradable conmigo, me entran recelos." },
  { id: 125, text: "Estoy orgulloso de mi sensatez." },
  { id: 126, text: "Con frecuencia acabo sintiéndome a disgusto con las personas con las que tengo que tratar." },
  { id: 127, text: "Prefiero los trabajos que me permiten trabajar solo, sin que me molesten los demás." },
  { id: 128, text: "La poesía tiene poco o ningún efecto sobre mí." },
  { id: 129, text: "Detestaría que alguien pensara de mí que soy un hipócrita." },
  { id: 130, text: "Parece que nunca soy capaz de organizarme." },
  { id: 131, text: "Cuando algo va mal, tiendo a culpabilizarme." },
  { id: 132, text: "Con frecuencia, los demás cuentan conmigo para tomar decisiones." },
  { id: 133, text: "Experimento una gran variedad de emociones o sentimientos." },
  { id: 134, text: "No se me conoce por mi generosidad." },
  { id: 135, text: "Cuando me comprometo a algo, siempre se puede contar conmigo para llevarlo a término." },
  { id: 136, text: "A menudo me siento inferior a los demás." },
  { id: 137, text: "No soy tan vivo ni tan animado como otras personas." },
  { id: 138, text: "Prefiero pasar el tiempo en ambientes conocidos." },
  { id: 139, text: "Cuando me han ofendido, lo que intento es perdonar y olvidar." },
  { id: 140, text: "No me siento impulsado a conseguir el éxito." },
  { id: 141, text: "Rara vez cedo a mis impulsos momentáneos." },
  { id: 142, text: "Me gusta estar donde está la acción." },
  { id: 143, text: "Me gusta hacer rompecabezas de los que te cuesta bastante resolverlos." },
  { id: 144, text: "Tengo una opinión muy alta de mí mismo." },
  { id: 145, text: "Cuando empiezo un proyecto, casi siempre lo termino." },
  { id: 146, text: "Con frecuencia me resulta difícil decidirme." },
  { id: 147, text: "No me considero especialmente alegre." },
  { id: 148, text: "Considero que la fidelidad a los propios ideales y principios es más importante que tener una mentalidad abierta." },
  { id: 149, text: "Las necesidades humanas deberían estar siempre por delante de consideraciones económicas." },
  { id: 150, text: "A menudo hago cosas siguiendo el impulso del momento." },
  { id: 151, text: "Me preocupo con frecuencia por cosas que podrían salir mal." },
  { id: 152, text: "Me resulta fácil sonreír y ser abierto con desconocidos." },
  { id: 153, text: "Si noto que mi mente comienza a divagar y a soñar, generalmente me ocupo en algo y empiezo a concentrarme en una tarea o actividad alternativa." },
  { id: 154, text: "Mi primera reacción es confiar en la gente." },
  { id: 155, text: "No parece que haya tenido éxito completo en algo." },
  { id: 156, text: "Es difícil que yo pierda los estribos." },
  { id: 157, text: "Preferiría pasar las vacaciones en una playa muy frecuentada que en una cabaña aislada en el bosque." },
  { id: 158, text: "Ciertos tipos de música me producen una fascinación sin límites." },
  { id: 159, text: "A veces consigo con artimañas que la gente haga lo que yo quiero." },
  { id: 160, text: "Tiendo a ser algo quisquilloso en el orden." },
  { id: 161, text: "Tengo una baja opinión de mí mismo." },
  { id: 162, text: "Preferiría ir a mi aire a ser el líder de otros." },
  { id: 163, text: "Rara vez me doy cuenta del humor o de las emociones que existen en cada ambiente." },
  { id: 164, text: "A la mayoría de las personas que conozco les caigo simpático." },
  { id: 165, text: "Me atengo de forma estricta a mis principios éticos." },
  { id: 166, text: "Me siento a gusto en presencia de mis jefes u otras figuras de autoridad." },
  { id: 167, text: "Habitualmente me parece tener prisa." },
  { id: 168, text: "A veces hago cambios en la casa sólo para probar algo diferente." },
  { id: 169, text: "Si alguien empieza a pelearse conmigo, yo también estoy dispuesto a pelear." },
  { id: 170, text: "Me esfuerzo por conseguir aquello para lo que estoy capacitado." },
  { id: 171, text: "A veces como tanto que me pongo malo." },
  { id: 172, text: "Adoro la excitación de las montañas rusas en los parques de atracciones." },
  { id: 173, text: "Tengo poco interés en andar pensando sobre la naturaleza del universo o de la condición humana." },
  { id: 174, text: "Pienso que no soy mejor que los demás, independientemente de cuál sea su condición." },
  { id: 175, text: "Cuando un proyecto se pone demasiado difícil, me siento inclinado a empezar uno nuevo." },
  { id: 176, text: "Puedo comportarme bastante bien en una crisis." },
  { id: 177, text: "Soy una persona alegre y animosa." },
  { id: 178, text: "Me considero de mentalidad abierta y tolerante con los estilos de los demás." },
  { id: 179, text: "Creo que todos los seres humanos merecen respeto." },
  { id: 180, text: "Casi nunca tomo decisiones precipitadas." },
  { id: 181, text: "Tengo menos miedos que la mayoría de la gente." },
  { id: 182, text: "Tengo unos fuertes lazos emocionales con mis amigos." },
  { id: 183, text: "De niño rara vez me divertía jugando a ser otra persona (policía, padre, profesor, etc.)." },
  { id: 184, text: "Tiendo a pensar lo mejor de la gente." },
  { id: 185, text: "Soy una persona muy competente." },
  { id: 186, text: "A veces me he sentido amargado y resentido." },
  { id: 187, text: "Las reuniones sociales normalmente me resultan aburridas." },
  { id: 188, text: "A veces, cuando leo poesía o contemplo una obra de arte, siento una profunda emoción o excitación." },
  { id: 189, text: "A veces intimido o adulo a la gente para que haga lo que yo quiero." },
  { id: 190, text: "No soy compulsivo sobre la limpieza." },
  { id: 191, text: "A veces las cosas me parecen demasiado sombrías y sin esperanza." },
  { id: 192, text: "En las conversaciones tiendo a ser el que más habla." },
  { id: 193, text: "Me parece fácil simpatizar, sentir yo lo que sienten los demás." },
  { id: 194, text: "Me considero una persona caritativa." },
  { id: 195, text: "Trato de hacer mis tareas con cuidado, para que no haya que hacerlas otra vez." },
  { id: 196, text: "Si he dicho o hecho algo mal a una persona, me cuesta mucho poder enfrentarme a ella de nuevo." },
  { id: 197, text: "Mi vida lleva un ritmo rápido." },
  { id: 198, text: "En vacaciones prefiero volver a un sitio conocido y fiable." },
  { id: 199, text: "Soy cabezota y testarudo." },
  { id: 200, text: "Me esfuerzo por llegar a la perfección en todo lo que hago." },
  { id: 201, text: "A veces hago las cosas impulsivamente y luego me arrepiento." },
  { id: 202, text: "Me atraen los colores llamativos y los estilos ostentosos." },
  { id: 203, text: "Tengo mucha curiosidad por los temas intelectuales." },
  { id: 204, text: "Preferiría elogiar a otros que ser elogiado." },
  { id: 205, text: "Hay tantas pequeñas cosas que hacer que a veces lo que hago es no atender a ninguna." },
  { id: 206, text: "Cuando parece que todo va mal, todavía puedo tomar buenas decisiones." },
  { id: 207, text: "Rara vez uso palabras como fantástico o sensacional para describir mis experiencias." },
  { id: 208, text: "Creo que si una persona no tiene claras sus creencias a los 25 años, algo no le va bien." },
  { id: 209, text: "Me inspiran simpatía los que son menos afortunados que yo." },
  { id: 210, text: "Cuando voy de viaje, lo planifico cuidadosamente con antelación." },
  { id: 211, text: "A veces me vienen a la mente pensamientos aterradores." },
  { id: 212, text: "Me tomo un interés personal por la gente con la que trabajo." },
  { id: 213, text: "Tendría dificultad para dejar que mi pensamiento vagara sin control o dirección." },
  { id: 214, text: "Tengo mucha fe en la naturaleza humana." },
  { id: 215, text: "Soy eficiente y eficaz en mi trabajo." },
  { id: 216, text: "Hasta las mínimas molestias me pueden resultar frustrantes." },
  { id: 217, text: "Disfruto en las fiestas en las que hay mucha gente." },
  { id: 218, text: "Disfruto leyendo poesías que se centran más en sentimientos e imágenes que en acontecimientos." },
  { id: 219, text: "Estoy orgulloso de mi astucia para tratar con la gente." },
  { id: 220, text: "Gasto un montón de tiempo buscando cosas que he perdido." },
  { id: 221, text: "Con demasiada frecuencia cuando las cosas van mal me siento desanimado y a punto de tirar la toalla." },
  { id: 222, text: "No me parece fácil asumir el control de una situación." },
  { id: 223, text: "Cosas raras o singulares (como ciertos olores o los nombres de lugares lejanos) pueden evocarme fuertes estados de ánimo." },
  { id: 224, text: "Me aparto de mi camino por ayudar a los demás, si puedo." },
  { id: 225, text: "Tendría que estar realmente enfermo para perder un día de trabajo." },
  { id: 226, text: "Cuando alguien que conozco hace tonterías, siento vergüenza ajena." },
  { id: 227, text: "Soy una persona muy activa." },
  { id: 228, text: "Cuando voy a alguna parte sigo siempre el mismo camino." },
  { id: 229, text: "Con frecuencia me enzarzo en discusiones con mi familia y mis compañeros." },
  { id: 230, text: "Soy un poco adicto al trabajo." },
  { id: 231, text: "Siempre soy capaz de mantener mis sentimientos bajo control." },
  { id: 232, text: "Me gusta ser parte del público en los acontecimientos deportivos." },
  { id: 233, text: "Tengo una gran variedad de intereses intelectuales." },
  { id: 234, text: "Soy una persona superior." },
  { id: 235, text: "Tengo mucha auto-disciplina." },
  { id: 236, text: "Soy bastante estable emocionalmente." },
  { id: 237, text: "Me río con facilidad." },
  { id: 238, text: "Considero que la nueva moralidad sobre lo que está permitido no es de ninguna manera una moralidad." },
  { id: 239, text: "Antes prefería ser conocido como una persona misericordiosa que como una persona recta." },
  { id: 240, text: "Antes de contestar una pregunta, me lo pienso dos veces." },
];
